## SPOKEO

## INPUTS
## URL TO PROFILE THAT NEEDS TO BE DELETED + EMAIL ADRESS TO SEND CONFIRMATION LINK TO

## OUTPUTS
## TYPE PROFILE URL INTO URL INPUT FIELD
## TYPE EMAIL ADRESS URL INTO EMAIL ADRESS FIELD

## MOVE MOUS TO IM NOT A ROBOT CHECKBOX
## CLICK IM NOT A ROBOT CHECKBOX

## CLICK REMOVE THIS LISTING